plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.9'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.beyond'
version = '0.0.1-SNAPSHOT'
description = 'basic project for Spring Boot'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
//gradle 빌드툴을 사용하더라도 저장소로 maven repository를 사용
repositories {
    mavenCentral()
}
//의존성(dependency) : 해당 프로젝트에서 사용할 라이브러리
dependencies {
//    spring 웹서비스(http)를 위한 기본 의존성
    implementation 'org.springframework.boot:spring-boot-starter-web'

//    getter, setter 등 개발에 편의성을 증대시켜주는 각종 어노테이션 포함하는 의존성
    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'

//    스프링에서 화면을 만들어 사용자에게 주는(MVC) 기술 중 하나
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'

//    db드라이버 : mariadb, mysql,oracle 등
    runtimeOnly 'org.mariadb.jdbc:mariadb-java-client'
//    db관리기술 : jdbc , mybatis, jpa(spring data jpa)
    implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'
    implementation 'org.mybatis.spring.boot:mybatis-spring-boot-starter:3.0.4'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
//    값 검증을 위한 의존성
    implementation 'org.springframework.boot:spring-boot-starter-validation'
//	로그인을 위한 security 의존성
//  security의존성을 적용하자마자 모든 api 요청에 대해 로그인을 요구(Authentication객체의 생성여부확인)
    implementation 'org.springframework.boot:spring-boot-starter-security'
//	jwt토큰 관련 라이브러리 추가
    implementation 'io.jsonwebtoken:jjwt-api:0.11.5'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.11.5'
// 	토큰의 JSON 인코딩/디코딩, 직렬화/파싱 에 필요
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.11.5'

//    아래는 테스트코드 작성을 위한 의존성
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}